### ISSUE TITLE
Help! Success in small data size and failed on large data size

### ISSUE THREAD

**Issue by 11721206** [undertheseanlp/text_to_speech#1]
Hi:
I parallel my code like you in Training.pl and Config.pm,I can run OK when my data size is 1000,but when my data size is 30000, it will error like this 
![image](https://user-images.githubusercontent.com/19368412/46937909-ef1a1000-d094-11e8-8769-80d77d6ec91d.png)
(::: some chunk run ok,but others fail).

I configure nj = 6.
$parallel = 1; # 0 mean off
$nj = 6;      # number of threads you want to run

additional:
when I set nj= 6;
all chunk will fail.
is there any suggestions for my question?

thanks a lot!

my Training.pl modified places are listed below:
if ($ERST0) {
  print_time("embedded reestimation (monophone)");

  if ($daem) {
     for ( $i = 1 ; $i <= $daem_nIte ; $i++ ) {
        for ( $j = 1 ; $j <= $nIte ; $j++ ) {

           # embedded reestimation
           $k = $j + ( $i - 1 ) * $nIte;
           print("\n\nIteration $k of Embedded Re-estimation\n");
           $k = ( $i / $daem_nIte )**$daem_alpha;
		   if($parallel){
			herest_par($mlf{'mon'},$lst{'mon'},$monommf{'cmp'},$monommf{'dur'}, $model{'cmp'},$model{'dur'},"-k $k","");
		   }
		   else{
			shell("$HERest{'mon'} -k $k -H $monommf{'cmp'} -N $monommf{'dur'} -M $model{'cmp'} -R $model{'dur'} $lst{'mon'} $lst{'mon'}");
		   }           
        }
     }
  }
  else {
     for ( $i = 1 ; $i <= $nIte ; $i++ ) {

        # embedded reestimation
        print("\n\nIteration $i of Embedded Re-estimation\n");
		if($parallel){
			herest_par($mlf{'mon'},$lst{'mon'},$monommf{'cmp'},$monommf{'dur'}, $model{'cmp'},$model{'dur'},"","");
			#herest_par($mlf{'mon'},$lst{'mon'},$monommf{'cmp'},$monommf{'dur'}, $model{'cmp'},$model{'dur'},"","");
		}
		else{
			shell("$HERest{'mon'} -H $monommf{'cmp'} -N $monommf{'dur'} -M $model{'cmp'} -R $model{'dur'} $lst{'mon'} $lst{'mon'}");		
		}        
     }
  }

  # compress reestimated model
  foreach $set (@SET) {
     shell("gzip -c $monommf{$set} > ${monommf{$set}}.embedded.gz");
  }
}

if ($ERST1) {
  print_time("embedded reestimation (fullcontext)");

  $opt = "-C $cfg{'nvf'} -s $stats{'cmp'} -w 0.0";

  # embedded reestimation
  print("\n\nEmbedded Re-estimation\n");
  if($parallel){
	herest_par($mlf{'ful'},$lst{'ful'},$fullmmf{'cmp'},$fullmmf{'dur'}, $model{'cmp'},$model{'dur'},"",$opt);
	#herest_par($mlf{'ful'},$lst{'ful'},$fullmmf{'cmp'},$fullmmf{'dur'}, $model{'cmp'},$model{'dur'},"",$opt);
  }
  else{
	shell("$HERest{'ful'} -H $fullmmf{'cmp'} -N $fullmmf{'dur'} -M $model{'cmp'} -R $model{'dur'} $opt $lst{'ful'} $lst{'ful'}");
  }  
  # compress reestimated model
  foreach $set (@SET) {
     shell("gzip -c $fullmmf{$set} > ${fullmmf{$set}}.embedded.gz");
  }
}

if ($ERST2) {
  print_time("embedded reestimation (clustered)");

  for ( $i = 1 ; $i <= $nIte ; $i++ ) {
     print("\n\nIteration $i of Embedded Re-estimation\n");
	 if($parallel){
	 herest_par($mlf{'ful'},$lst{'ful'},$clusmmf{'cmp'},$clusmmf{'dur'}, $model{'cmp'},$model{'dur'},"","");
	 }
	 else{
	 shell("$HERest{'ful'} -H $clusmmf{'cmp'} -N $clusmmf{'dur'} -M $model{'cmp'} -R $model{'dur'} $lst{'ful'} $lst{'ful'}");
	 }     
  }

  # compress reestimated mmfs
  foreach $set (@SET) {
     shell("gzip -c $clusmmf{$set} > $clusmmf{$set}.embedded.gz");
  }
}

if ($ERST3) {
  print_time("embedded reestimation (untied)");

  $opt = "-C $cfg{'nvf'} -s $stats{'cmp'} -w 0.0";

  print("\n\nEmbedded Re-estimation for untied mmfs\n");
  if($parallel){
  herest_par($mlf{'ful'},$lst{'ful'},$untymmf{'cmp'},$untymmf{'dur'}, $model{'cmp'},$model{'dur'},"",$opt);  
  }
  else{
  shell("$HERest{'ful'} -H $untymmf{'cmp'} -N $untymmf{'dur'} -M $model{'cmp'} -R $model{'dur'} $opt $lst{'ful'} $lst{'ful'}");
  }  
}

if ($ERST4) {
  print_time("embedded reestimation (re-clustered)");

  for ( $i = 1 ; $i <= $nIte ; $i++ ) {
     print("\n\nIteration $i of Embedded Re-estimation\n");
	 if($parallel){
	 herest_par($mlf{'ful'},$lst{'ful'},$reclmmf{'cmp'},$reclmmf{'dur'}, $model{'cmp'},$model{'dur'},"");
	 }
	 else{	 
     shell("$HERest{'ful'} -H $reclmmf{'cmp'} -N $reclmmf{'dur'} -M $model{'cmp'} -R $model{'dur'} $lst{'ful'} $lst{'ful'}");
	 }
  }

  # compress reestimated mmfs
  foreach $set (@SET) {
     shell("gzip -c $reclmmf{$set} > $reclmmf{$set}.embedded.gz");
  }
}

sub herest_par {
    # Parameters:
    # @mlf  :   label mlf files such as full.mlf ($mlf{'full'})
    # @list :   list of full context label. e.g
    # @in_cmp:  input model of cmp features to HERest
    # @in_dur:  input model of duration features to HERest
    # @out_cmp: output model of cmp features
    # @out_dur: output model of duration features
    # @param:   additional params for HERest. e.g -k 4
    # @report_stat: use to report stats file for building trees
    #

    # Usages examples:
    # step: ERST0
    #     herest_par($mlf{'mon'},$lst{'mon'},$monommf{'cmp'},$monommf{'dur'}, $model{'cmp'},$model->{'dur'},"-k $k","");
    # step: ERST1
    #     $opt = "-C $cfg{'nvf'} -s $stats{'cmp'} -w 0.0";
    #     herest_par($mlf{'ful'},$lst{'ful'},$fullmmf{'cmp'},$fulmmf{'dur'}, $model{'cmp'},$model->{'dur'},"",$opt);
    #

  my ($mlf,$list,$in_cmp,$in_dur,$out_cmp,$out_dur,$param,$report_stat) = @_;

    if ($parallel){
       my $pm = new Parallel::ForkManager($nj);
         $pm->run_on_finish( sub {
            my ($pid, $exit_code, $ident) = @_;
            if ($exit_code != 0) {
                exit $exit_code;
            }
         });	   
       for (my $i=1; $i < $nj+1; $i++) {
          $pm->start and next; # do the fork
          shell("$HERest $param -S $prjdir/tmp/$files[$i-1] -I $mlf -H $in_cmp -N $in_dur -M $out_cmp -R $out_dur -p $i $list $list");

          $pm->finish;
       }
       $pm->wait_all_children;

      my $directory = dirname( "$in_cmp" );
      opendir DIR, $directory or die "cannot open dir $dir: $!";
      my @files = grep { index($_, 'hmm') != -1 } readdir DIR;
      $acc="";
      foreach (@files){
          $dur = $_;
          $dur =~ s/hmm/dur/g;
          $acc.=" $directory/".$_." $directory/$dur";
      }
        if ($report_stat){
          shell("$HERest -H $in_cmp -N $in_dur -M $out_cmp -R $out_dur -p 0 $report_stat $list $list $acc");
        }else{
          shell("$HERest -H $in_cmp -N $in_dur -M $out_cmp -R $out_dur -p 0 $list $list $acc");
        }
      system("rm $directory/*.acc");
    }else{
        if ($report_stat){
          shell("$HERest -S $scp{'trn'} -I $mlf -H $in_cmp -N $in_dur -M $out_cmp -R $out_dur $report_stat $list $list");
        }else{
            shell("$HERest $param -S $scp{'trn'} -I $mlf -H $in_cmp -N $in_dur -M $out_cmp -R $out_dur  $list $list");
        }
    }
}

thanks a lot

**Comment by truongdo** [comment]
With that big data set, I suspect that you ran out of memory.

**Comment by 11721206** [comment]
> With that big data set, I suspect that you ran out of memory.

but when parallel model is disabled. code runs successfully in big data set.Only When in parallel mode,  the error will occur.
is there any tips for my questions?
thx

**Comment by truongdo** [comment]
No matter how many threads you use for the training, each thread will use a fixed amount of memory ( let say 2GB).
When you run 10 threads, it will eat 2 * 10 = 20GB of memory.

The easiest way is to upgrade RAM or to use a smaller number of threads.
